### ISSUE TITLE
README improvement

### ISSUE THREAD

**Issue by arnaudstiegler** [arthurherbout/crypto_code_detection#23]
Re-using the intro of the report as an introduction of the README. Would also be great to start thinking about repo structure before it gets out-of-hand

**Comment by arthurherbout** [comment]
for the structure, I would suggest to do:
- data (already done)
- models
----------> model1
-------------------------> files for model1
----------> model2
-------------------------> files for model2
etc
I think we should not have raw files at the root of the directory.

**Comment by redouane-dziri** [comment]
OK got started on the README, close this if no longer needed
