### ISSUE TITLE
Issue with file name in aggregated files

### ISSUE THREAD

**Issue by arnaudstiegler** [arthurherbout/crypto_code_detection#31]
@corentinllorca, @redouane-dziri, 
Not sure who's in charge for that, but file names for crypto-library are root paths, and it's not very convenient for QA'ing the results

**Comment by Hadrien-Cornier** [comment]
Indeed
`test=pd.read_json('C:/Users/hadri/Documents/GitHub/crypto_code_detection/data/full_data.json')
print(test.iloc[0]['file_name'])
'/Users/red/Documents/CP/crypto_code_detection/data/crypto-library/files/nettle/eddsa-hash.c' `

**Comment by arnaudstiegler** [comment]
I fixed the file name for the crypto-library on my branch, will merge soon with newly generated full_data.json. However, couldn't run the train_test .py file for now so the train.json and test.json are still the old version on my branch

**Comment by redouane-dziri** [comment]
The only issue is with files from `crypto-library` right? 
@arnaudstiegler you're saying this is fixed locally for you then? :) If yes let us know when this is merged and fixed on master

**Comment by redouane-dziri** [comment]
Ok so need to look at generations of test and train

**Comment by redouane-dziri** [comment]
PR #38 should've fixed this, and I re-generated all the necessary jsons in it. Close this when you want.
