### ISSUE TITLE
(1) Extract cryptography files from the crypto competitions

### ISSUE THREAD

**Issue by corentinllorca** [arthurherbout/crypto_code_detection#4]
See #1

**Comment by redouane-dziri** [comment]
Extracted C code from the following:

CAESAR

- https://github.com/ascon/ascon_collection 
- https://github.com/crocs-muni/CryptoStreams_CAESAR 
- https://github.com/dkales/caesar-nonce-misuse 
- https://github.com/SparkDustJoe/NorxManaged 
- https://github.com/jasdheer/ICEPOLE-Cipher-Optimization 
- https://github.com/SparkDustJoe/MorusManaged 

SHA-3

- https://github.com/ajakubek/python-sha3 
- https://github.com/stuartcalder/3crypt 

PHC

- https://github.com/bsdphk/PHC 

NIST

- https://github.com/sebastien-riou/DryGASCON 

AND https://embeddedsw.net/Cipher_Reference_Home.html 

Manually checked to avoid False Positives (pretty restrictive the proportion of FP should be very - very - low). Got about ~300 files total. 

Also:
- http://hms.isi.jhu.edu/acsc/damgard-jurik/ (Damgârd-Jurik Cryptosystem)
- http://hms.isi.jhu.edu/acsc/piratte/ (PIRATTE: Proxy-based Immediate Revocation of ATTribute-based Encryption)

**Comment by redouane-dziri** [comment]
See #9

**Comment by redouane-dziri** [comment]
Merged and done
