### ISSUE TITLE
(1) Extract non-cryptography files from CodeJam

### ISSUE THREAD

**Issue by corentinllorca** [arthurherbout/crypto_code_detection#5]
See #1

**Comment by arthurherbout** [comment]
I started this task. 
The dataset I got is quite big (16G) so we need to find a way of taking a subsample.

Issues with the dataset:
- It is divided into problems so there will be a lot of duplicates. 
- all languages. We need to decide on which languages to keep. Only c, c++? What about .h files?

I am currently exploring the dataset to get a good feeling about it.

**Comment by redouane-dziri** [comment]
Let's get .c, .cpp, .h and .hpp if there are some! We decided on fetching 20 samples from each problems to get started. Hopefully there won't be too many duplicates and redundancies

**Comment by redouane-dziri** [comment]
Merged and done
